/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiGenerateThumbnailRouteImport } from './routes/api/generate-thumbnail'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/_admin/index'
import { Route as AuthenticatedAdminTrendsRouteImport } from './routes/_authenticated/_admin/trends'
import { Route as AuthenticatedAdminSourcingRouteImport } from './routes/_authenticated/_admin/sourcing'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/_admin/settings'
import { Route as AuthenticatedAdminRiskRouteImport } from './routes/_authenticated/_admin/risk'
import { Route as AuthenticatedAdminReviewRouteImport } from './routes/_authenticated/_admin/review'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/_admin/products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/_admin/orders'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/_admin/inventory'
import { Route as AuthenticatedAdminCompetitionRouteImport } from './routes/_authenticated/_admin/competition'
import { Route as ApiPublicHooksSyncInventoryRouteImport } from './routes/api/public/hooks/sync-inventory'
import { Route as ApiPublicHooksSourceProductsRouteImport } from './routes/api/public/hooks/source-products'
import { Route as ApiPublicHooksProcessOrdersRouteImport } from './routes/api/public/hooks/process-orders'
import { Route as ApiPublicHooksKiprisScanRouteImport } from './routes/api/public/hooks/kipris-scan'
import { Route as ApiPublicHooksDailyPipelineRouteImport } from './routes/api/public/hooks/daily-pipeline'
import { Route as ApiPublicHooksCollectTrendsRouteImport } from './routes/api/public/hooks/collect-trends'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateThumbnailRoute = ApiGenerateThumbnailRouteImport.update({
  id: '/api/generate-thumbnail',
  path: '/api/generate-thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTrendsRoute =
  AuthenticatedAdminTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSourcingRoute =
  AuthenticatedAdminSourcingRouteImport.update({
    id: '/sourcing',
    path: '/sourcing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRiskRoute = AuthenticatedAdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompetitionRoute =
  AuthenticatedAdminCompetitionRouteImport.update({
    id: '/competition',
    path: '/competition',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksSyncInventoryRoute =
  ApiPublicHooksSyncInventoryRouteImport.update({
    id: '/api/public/hooks/sync-inventory',
    path: '/api/public/hooks/sync-inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSourceProductsRoute =
  ApiPublicHooksSourceProductsRouteImport.update({
    id: '/api/public/hooks/source-products',
    path: '/api/public/hooks/source-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessOrdersRoute =
  ApiPublicHooksProcessOrdersRouteImport.update({
    id: '/api/public/hooks/process-orders',
    path: '/api/public/hooks/process-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKiprisScanRoute =
  ApiPublicHooksKiprisScanRouteImport.update({
    id: '/api/public/hooks/kipris-scan',
    path: '/api/public/hooks/kipris-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyPipelineRoute =
  ApiPublicHooksDailyPipelineRouteImport.update({
    id: '/api/public/hooks/daily-pipeline',
    path: '/api/public/hooks/daily-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCollectTrendsRoute =
  ApiPublicHooksCollectTrendsRouteImport.update({
    id: '/api/public/hooks/collect-trends',
    path: '/api/public/hooks/collect-trends',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-thumbnail': typeof ApiGenerateThumbnailRoute
  '/competition': typeof AuthenticatedAdminCompetitionRoute
  '/inventory': typeof AuthenticatedAdminInventoryRoute
  '/orders': typeof AuthenticatedAdminOrdersRoute
  '/products': typeof AuthenticatedAdminProductsRoute
  '/review': typeof AuthenticatedAdminReviewRoute
  '/risk': typeof AuthenticatedAdminRiskRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/sourcing': typeof AuthenticatedAdminSourcingRoute
  '/trends': typeof AuthenticatedAdminTrendsRoute
  '/api/public/hooks/collect-trends': typeof ApiPublicHooksCollectTrendsRoute
  '/api/public/hooks/daily-pipeline': typeof ApiPublicHooksDailyPipelineRoute
  '/api/public/hooks/kipris-scan': typeof ApiPublicHooksKiprisScanRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/source-products': typeof ApiPublicHooksSourceProductsRoute
  '/api/public/hooks/sync-inventory': typeof ApiPublicHooksSyncInventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-thumbnail': typeof ApiGenerateThumbnailRoute
  '/competition': typeof AuthenticatedAdminCompetitionRoute
  '/inventory': typeof AuthenticatedAdminInventoryRoute
  '/orders': typeof AuthenticatedAdminOrdersRoute
  '/products': typeof AuthenticatedAdminProductsRoute
  '/review': typeof AuthenticatedAdminReviewRoute
  '/risk': typeof AuthenticatedAdminRiskRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/sourcing': typeof AuthenticatedAdminSourcingRoute
  '/trends': typeof AuthenticatedAdminTrendsRoute
  '/api/public/hooks/collect-trends': typeof ApiPublicHooksCollectTrendsRoute
  '/api/public/hooks/daily-pipeline': typeof ApiPublicHooksDailyPipelineRoute
  '/api/public/hooks/kipris-scan': typeof ApiPublicHooksKiprisScanRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/source-products': typeof ApiPublicHooksSourceProductsRoute
  '/api/public/hooks/sync-inventory': typeof ApiPublicHooksSyncInventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/generate-thumbnail': typeof ApiGenerateThumbnailRoute
  '/_authenticated/_admin/competition': typeof AuthenticatedAdminCompetitionRoute
  '/_authenticated/_admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/_admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/_admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/_admin/review': typeof AuthenticatedAdminReviewRoute
  '/_authenticated/_admin/risk': typeof AuthenticatedAdminRiskRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/_admin/sourcing': typeof AuthenticatedAdminSourcingRoute
  '/_authenticated/_admin/trends': typeof AuthenticatedAdminTrendsRoute
  '/_authenticated/_admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/collect-trends': typeof ApiPublicHooksCollectTrendsRoute
  '/api/public/hooks/daily-pipeline': typeof ApiPublicHooksDailyPipelineRoute
  '/api/public/hooks/kipris-scan': typeof ApiPublicHooksKiprisScanRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/source-products': typeof ApiPublicHooksSourceProductsRoute
  '/api/public/hooks/sync-inventory': typeof ApiPublicHooksSyncInventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/generate-thumbnail'
    | '/competition'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/review'
    | '/risk'
    | '/settings'
    | '/sourcing'
    | '/trends'
    | '/api/public/hooks/collect-trends'
    | '/api/public/hooks/daily-pipeline'
    | '/api/public/hooks/kipris-scan'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/source-products'
    | '/api/public/hooks/sync-inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/generate-thumbnail'
    | '/competition'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/review'
    | '/risk'
    | '/settings'
    | '/sourcing'
    | '/trends'
    | '/api/public/hooks/collect-trends'
    | '/api/public/hooks/daily-pipeline'
    | '/api/public/hooks/kipris-scan'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/source-products'
    | '/api/public/hooks/sync-inventory'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/api/generate-thumbnail'
    | '/_authenticated/_admin/competition'
    | '/_authenticated/_admin/inventory'
    | '/_authenticated/_admin/orders'
    | '/_authenticated/_admin/products'
    | '/_authenticated/_admin/review'
    | '/_authenticated/_admin/risk'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/sourcing'
    | '/_authenticated/_admin/trends'
    | '/_authenticated/_admin/'
    | '/api/public/hooks/collect-trends'
    | '/api/public/hooks/daily-pipeline'
    | '/api/public/hooks/kipris-scan'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/source-products'
    | '/api/public/hooks/sync-inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGenerateThumbnailRoute: typeof ApiGenerateThumbnailRoute
  ApiPublicHooksCollectTrendsRoute: typeof ApiPublicHooksCollectTrendsRoute
  ApiPublicHooksDailyPipelineRoute: typeof ApiPublicHooksDailyPipelineRoute
  ApiPublicHooksKiprisScanRoute: typeof ApiPublicHooksKiprisScanRoute
  ApiPublicHooksProcessOrdersRoute: typeof ApiPublicHooksProcessOrdersRoute
  ApiPublicHooksSourceProductsRoute: typeof ApiPublicHooksSourceProductsRoute
  ApiPublicHooksSyncInventoryRoute: typeof ApiPublicHooksSyncInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-thumbnail': {
      id: '/api/generate-thumbnail'
      path: '/api/generate-thumbnail'
      fullPath: '/api/generate-thumbnail'
      preLoaderRoute: typeof ApiGenerateThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/': {
      id: '/_authenticated/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/trends': {
      id: '/_authenticated/_admin/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedAdminTrendsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/sourcing': {
      id: '/_authenticated/_admin/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AuthenticatedAdminSourcingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/risk': {
      id: '/_authenticated/_admin/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedAdminRiskRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/review': {
      id: '/_authenticated/_admin/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/products': {
      id: '/_authenticated/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/orders': {
      id: '/_authenticated/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/inventory': {
      id: '/_authenticated/_admin/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/competition': {
      id: '/_authenticated/_admin/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof AuthenticatedAdminCompetitionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/sync-inventory': {
      id: '/api/public/hooks/sync-inventory'
      path: '/api/public/hooks/sync-inventory'
      fullPath: '/api/public/hooks/sync-inventory'
      preLoaderRoute: typeof ApiPublicHooksSyncInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/source-products': {
      id: '/api/public/hooks/source-products'
      path: '/api/public/hooks/source-products'
      fullPath: '/api/public/hooks/source-products'
      preLoaderRoute: typeof ApiPublicHooksSourceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-orders': {
      id: '/api/public/hooks/process-orders'
      path: '/api/public/hooks/process-orders'
      fullPath: '/api/public/hooks/process-orders'
      preLoaderRoute: typeof ApiPublicHooksProcessOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kipris-scan': {
      id: '/api/public/hooks/kipris-scan'
      path: '/api/public/hooks/kipris-scan'
      fullPath: '/api/public/hooks/kipris-scan'
      preLoaderRoute: typeof ApiPublicHooksKiprisScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-pipeline': {
      id: '/api/public/hooks/daily-pipeline'
      path: '/api/public/hooks/daily-pipeline'
      fullPath: '/api/public/hooks/daily-pipeline'
      preLoaderRoute: typeof ApiPublicHooksDailyPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/collect-trends': {
      id: '/api/public/hooks/collect-trends'
      path: '/api/public/hooks/collect-trends'
      fullPath: '/api/public/hooks/collect-trends'
      preLoaderRoute: typeof ApiPublicHooksCollectTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCompetitionRoute: typeof AuthenticatedAdminCompetitionRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute
  AuthenticatedAdminRiskRoute: typeof AuthenticatedAdminRiskRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSourcingRoute: typeof AuthenticatedAdminSourcingRoute
  AuthenticatedAdminTrendsRoute: typeof AuthenticatedAdminTrendsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCompetitionRoute: AuthenticatedAdminCompetitionRoute,
    AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
    AuthenticatedAdminRiskRoute: AuthenticatedAdminRiskRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSourcingRoute: AuthenticatedAdminSourcingRoute,
    AuthenticatedAdminTrendsRoute: AuthenticatedAdminTrendsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGenerateThumbnailRoute: ApiGenerateThumbnailRoute,
  ApiPublicHooksCollectTrendsRoute: ApiPublicHooksCollectTrendsRoute,
  ApiPublicHooksDailyPipelineRoute: ApiPublicHooksDailyPipelineRoute,
  ApiPublicHooksKiprisScanRoute: ApiPublicHooksKiprisScanRoute,
  ApiPublicHooksProcessOrdersRoute: ApiPublicHooksProcessOrdersRoute,
  ApiPublicHooksSourceProductsRoute: ApiPublicHooksSourceProductsRoute,
  ApiPublicHooksSyncInventoryRoute: ApiPublicHooksSyncInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
